heroku/languages-github-actions

- Cargo.toml
Before:
```
$ ls -lh target/release/actions
-rwxr-xr-x 1 emorley staff 4.1M Jun 22 09:59 target/release/actions
```
After:
```
$ ls -lh target/release/actions
-rwxr-xr-x 1 emorley staff 3.0M Jun 22 10:01 target/release/actions
```
See:
https://doc.rust-lang.org/stable/cargo/reference/profiles.html#strip
> Strip the release binary

- .github/actions/prepare-release/action.yml
- .github/actions/prepare-release/index.js
- Cargo.lock
- Cargo.toml
- README.md
- src/changelog.rs
- src/commands/prepare_release/command.rs
- src/commands/prepare_release/errors.rs
The optional argument `--declarations-starting-version` has been added to the `actions prepare-release` command to limit the declarations created when rebuilding the `CHANGELOG.md` file into the Keep A Changelog format.
Buildpacks that are only now normalizing on fixed versions and release tags (e.g.; [`buildpacks-jvm`](https://github.com/heroku/buildpacks-jvm), [`buildpacks-nodejs`](https://github.com/heroku/buildpacks-nodejs)) can use this to prevent invalid declaration links from being generated.
> Add --declarations-starting-version arg to prepare-release

- .github/workflows/_buildpacks-release-update-builder.yml
Drops the version from the branch created. We don't have that information here not that it isn't run with as part of a strategy.
> Fix update builder workflow branch name

- src/buildpacks.rs
- src/commands/generate_buildpack_matrix/command.rs
- src/commands/generate_changelog/command.rs
- src/commands/prepare_release/command.rs
- src/commands/update_builder/command.rs
All of our buildpacks should be following the Keep-a-Changelog format so filtering detected buildpacks by directories that contain both `buildpack.toml` and `CHANGELOG.md` seems like a sensible choice.
This also eliminates some of the extra buildpack directories that are being picked up in [`heroku/buildpacks-nodejs`](https://github.com/heroku/buildpacks-nodejs).
> Only run actions against buildpacks that also contain a CHANGELOG.md

- Cargo.lock
- Cargo.toml
- src/buildpacks.rs
- src/changelog.rs
- src/commands/generate_changelog/command.rs
- src/commands/prepare_release/command.rs
- src/commands/prepare_release/errors.rs
- src/commands/update_builder/command.rs
- src/main.rs
Most of the changes were generated by `cargo clippy --fix`.
I've added a temporary `allow(clippy::option_option)` since resolving that lint error will require a refactor, so worth handling separately.
Fixes #36.
GUS-W-13664629.
> Enable additional rustc/Clippy lints

- .github/workflows/_buildpacks-release-package.yml
Sets the `CARGO_TERM_COLOR` environment variable in the `package` workflow so we get colorized output from `cargo` commands.
@fixes #52
> Enable colorized cargo output

- .github/workflows/_buildpacks-release-package.yml
The `setup-tools` step was previously used to install `yj` and extract metadata from the buildpack during the `package` workflow but this is no longer required since that metadata is now extracted as part of the `detect` workflow.
@fixes #51
> Remove setup-tools step from package workflow

- .github/actions/restore-buildpack-release/action.yml
Previously if any of the cache restore steps failed due to a timeout, the restore step would only emit a warning, and then the job would continue onto later steps that will fail if the restored files don't exist.
Now:
* If the cache cannot be restored, the cache restore step itself will correctly fail (since we need the restored files).
* The timeout has also been reduced from 10 minutes to 1 minute, so the job fails (and can be retried) sooner.
See:
https://github.com/actions/cache/tree/main/restore
This is a port of the improvements in:
https://github.com/heroku/builder/pull/360
Fixes #61.
GUS-W-13738824.
> Improve the UX for GHA cache restore timeout errors

- .github/workflows/_buildpacks-release-update-builder.yml
This will replace the default `[create-pull-request] automated change` commit message with the details of what is actually in the commit.
Fixes #50, [GUS:W-13738729](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001Vs0bqYAB/view)
> Set commit message on PR to heroku/builder

- .github/workflows/_buildpacks-prepare-release.yml
- .github/workflows/_buildpacks-release-package.yml
- .github/workflows/_buildpacks-release-publish-docker.yml
- .github/workflows/_buildpacks-release-publish-github.yml
- .github/workflows/_buildpacks-release-update-builder.yml
- .github/workflows/build-test-release.yml
For security and determinism reasons.
Dependabot will then open PRs when they need updating, which we can carefully review before merging.
Fixes #73.
GUS-W-13795910.
> Pin third-party GitHub Actions to specific patch versions

- .github/workflows/_buildpacks-release-publish-cnb-registry.yml
Dependabot can currently only update standard actions, not those that use a Docker Hub reference - so this Docker Hub reference has to be updated manually.
The upstream `request-add-entry` action has a number of fixes we should pick up:
https://github.com/buildpacks/github-actions/compare/v5.0.1...v5.3.0
Most notably:
- https://github.com/buildpacks/github-actions/pull/198
- https://github.com/buildpacks/github-actions/pull/214
Fixes #68.
GUS-W-13788681.
> Update to request-add-entry action v5.3.0

- .github/workflows/_buildpacks-release-publish-cnb-registry.yml
The image tag `5.3.0` cannot be found currently. Unsure if we updated without checking it actually exists or if the tag was removed after the fact. In any case, this PR downgrades to the latest version that is available on ghcr.io to unblock users of the actions.
Ref: https://github.com/heroku/languages-github-actions/pull/69
> Downgrade request-add-entry action to v5.2.0

- src/changelog.rs
Previously if the changelog y/m/d were out of order this error would occur:
```
Error: Invalid date in release entry
```
With this change it now gives much more context:
```
Error: Invalid date in release entry - Could not convert year: 2023, month: 31, day: 1 into a valid date from "[2.0.0] 2023/31/01"
```
> Give more information on failure

- Cargo.lock
- Cargo.toml
- src/buildpacks.rs
- src/commands/generate_buildpack_matrix/command.rs
- src/commands/update_builder/command.rs
This is a backwards-compatible fix to allow for our buildpacks to migrate away from `[metadata.release.docker]` to define our `repository` location in favor of the more agnostic `[metadata.release.image]`.
Fixes #45, [W-13738734](https://gus.lightning.force.com/a07EE00001Vrz9cYAB)
> Use [metadata.release.image] for repository key

- src/commands/prepare_release/command.rs
Meta-buildpacks can have multiple order group that list the same buildpack ids.  This PR switches the list of buildpack ids that have been updated from a `Vec<BuildpackId>` to a `HashSet<BuildpackId>` to prevent duplicate entries from ending up in changelogs.
Fixes #70, [W-13792776](https://gus.lightning.force.com/a07EE00001WZQhJYAX)
> Use HashSet for list of changed buildpack ids

- src/buildpacks.rs
We can remove this fallback key for reading the repository to publish to now that the following PRs have been merged:
- https://github.com/heroku/buildpacks-go/pull/124
- https://github.com/heroku/buildpacks-php/pull/15
- https://github.com/heroku/buildpacks-ruby/pull/184
- https://github.com/heroku/buildpacks-jvm/pull/555
- https://github.com/heroku/buildpacks-nodejs/pull/610
- https://github.com/heroku/buildpacks-python/pull/58
- https://github.com/heroku/procfile-cnb/pull/156
> Post PR #88 Cleanup

- .github/workflows/_buildpacks-prepare-release.yml
- .github/workflows/_buildpacks-release.yml
Previously the automation included the buildpack release version in the branch name used for both the "Prepare release" and "Update builder" PRs.
For example:
`prepare/v0.1.7`
`update/heroku/buildpacks-go/0.1.7`
This meant that multiple PRs can end up being opened, for example if:
- Someone triggers a "Prepare release" PR, but then triggers another with a different bump level (such as if they realised they had chosen the wrong version bump initiall)
- The "Update builder" PR is not merged for one release, before the next release occurs (as seen in ).
Now, the branch names no longer include the buildpack version, for example:
`prepare-release`
`update/heroku/buildpacks-go`
...meaning that the initial PR gets updated instead, per:
https://github.com/peter-evans/create-pull-request#action-beh …
> Use a consistent branch name when opening PRs

- .github/workflows/_buildpacks-prepare-release.yml
Since:
- The PR is opened by a bot account, so it's already clear that it's not been triggered by a human.
- The `create-pull-request` action doesn't add the label at time of PR creation and instead [adds it shortly after](https://github.com/peter-evans/create-pull-request/blob/3f6dd507d6db1a5a5de747205453b550f1da8dbc/src/github-helper.ts#L137-L145), which causes an unnecessary second triggering of any CI checks that listen to the `labelled` event (such as the Check Changelog Action).
Example duplicate Check Changelog run:
> Don't add the `automation` label to prepare release PRs

- .github/workflows/_buildpacks-prepare-release.yml
- .github/workflows/_buildpacks-release.yml
Previously the changelog for a CNB release was only included in the PR descriptions, and not the commit message. 
Now the changelog is included in the commit message too, which means it's possible to understand what changed when looking at the commit view, without needing to open up the PR to read there instead.
GUS-W-13912483.
> Include the release changelog in the commit message too

- .github/workflows/_buildpacks-release.yml
Changes the GitHub release process from being performed using a strategy for each buildpack which would perform partial overwrites of the release details and assets to packaging all the `*.cnb` files using a bash loop + `jq` and creating a single release with all the assets attached.
With this modification, a guard check can now be added to check if the release exists before attempting to create the release.  The "Create GitHub Release" step will be skipped if the release already exists or we're running the actions in `dry_run=true` mode. This should prevent a GH release from being clobbered if the release workflow is accidentally triggered without running the prepare release workflow first.
Fixes #89, [W-13871126](https://gus.lightning.force.com/a07EE00001XRghXYAT)
> Fix GitHub publish

- .github/workflows/_buildpacks-release.yml
- Cargo.toml
The workflows in this repo use libcnb in two ways:
1. As a library (specifically `libcnb-package` and `libcnb-data`)
2. As a binary (`cargo libcnb package`)
The version of (1) is controlled by `Cargo.toml` / `Cargo.lock` in this repo.
Previously the version of (2) wasn't pinned at all, and instead the latest version would be used, meaning that version could get out of sync with that of (1).
Now, the version is manually pinned to the same version as in `Cargo.toml`.
Longer term this should either be replaced by deriving the version in the workflow, or at least having a CI check/lint that ensures the two are in sync.
However, for the short term we want to just fix CNB releases after the 0.14.0 libcnb release, until we have time to make the necessary changes in #120.
> Pin the `libcnb-cargo` version to the same version as `libcnb-package`

- src/changelog.rs
Since the latest version is v1.1.0:
https://keepachangelog.com
Note the website example doesn't show this due to:
https://github.com/olivierlacan/keep-a-changelog/issues/567
> Update the template keepachangelog.com URL to v1.1.0

- src/commands/prepare_release/command.rs
Unfortunately with the current design of `prepare-release` it's not easy to test this, so I was not able to add a test.
Fixes #127.
GUS-W-13981097.
> Fix missing trailing newline in generated CHANGELOG.md

- .github/dependabot.yml
Previously only libcnb related dependency updates were grouped into one Dependabot PR.
Now there is a second group, that takes advantage of Dependabot's new semver version level grouping feature:
https://github.blog/changelog/2023-08-17-grouped-version-updates-by-semantic-version-level-for-dependabot/
GUS-W-13990911.
> Group minor/patch version Rust Dependabot updates into one PR

- .github/workflows/_buildpacks-prepare-release.yml
- .github/workflows/_buildpacks-release.yml
The previous configuration worked if commits were done manually with a `git commit ...` but the [peter-evans/create-pull-request](https://github.com/peter-evans/create-pull-request) action will use the GitHub Actions bot as committer and the user that triggered the workflow as author if  `committer` and `author` are not given as inputs.
Fixes #132 
GUS-W-14041925.
> Fix bot commit signing

- .github/actions/install-languages-cli/action.yml
- .github/workflows/_buildpacks-prepare-release.yml
- .github/workflows/_buildpacks-release.yml
- README.md
This PR exposes inputs on the release workflow (`languages_cli_branch`) that allow a `branch` to be passed through to the `install-languages-cli` action.
For automations that invoke these reusable workflows, this will allow CLI changes to be tested from a feature branch before they are merged into `main`.
Fixes #106 
GUS-W-13955891.
> Allow testing of CLI changes from a branch

- .github/workflows/_buildpacks-release.yml
Switched `curl` invocation to use head request, handle retries on error, return exit code, etc.
Fixes #139
> Use curl best practices for CNB registry check

- .github/workflows/_buildpacks-release.yml
Adds the two new builder image variants recently added to the `heroku/builder` repo:
- https://github.com/heroku/builder/pull/392
- https://github.com/heroku/builder/pull/394
GUS-W-14185090.
> Add the new builder image variants to the `builder.toml` update list

- .github/workflows/_buildpacks-release.yml
- README.md
- src/commands/update_builder/command.rs
Since the repository has been renamed:
https://github.com/heroku/cnb-builder-images/issues/396
GUS-W-14201543.
> Update builder repo name to cnb-builder-images

- src/commands/prepare_release/command.rs
- will merge the updated buildpack versions with any existing `Changed` entries
- otherwise will create a new `Changed` header containing the updated buildpack versions
Fixes #130
> Adds `Changed` header to buildpack version updates

- src/changelog.rs
- src/commands/generate_changelog/command.rs
- src/commands/prepare_release/command.rs
Fixes the following which are new in Rust 1.73:
```
error: use of `or_insert_with` to construct default value
--> src/changelog.rs:53:38
|
53 | ...                   .or_insert_with(Vec::new);
|                        ^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `or_default()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unwrap_or_default
= note: `-D clippy::unwrap-or-default` implied by `-D warnings`
error: use of `or_insert_with` to construct default value
--> src/changelog.rs:63:26
|
63 |                         .or_insert_with(Vec::new);
|                          ^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `or_default()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unwrap_or_default
```
And these …
> Fix lint errors in Rust 1.73 and 1.74

- .github/workflows/_buildpacks-prepare-release.yml
- .github/workflows/_buildpacks-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Enable Bash `pipefail` mode by setting an explicit GitHub Actions shell
- Pass `--exit-status` to all `jq` invocations, so it actually exits non-zero on empty input
See:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell https://jqlang.github.io/jq/manual/#invoking-jq
GUS-W-14249448.
> Apply some reliability/failure UX best practices

- README.md
- src/buildpacks.rs
- src/commands/generate_buildpack_matrix/command.rs
- src/commands/generate_buildpack_matrix/errors.rs
- src/commands/update_builder/command.rs
- src/commands/update_builder/errors.rs
As of #88 the metadata is now under `image.repository` not `docker.repository`, however, the error message still referenced the old location.
This caused confusion in when debugging heroku/buildpacks-jvm#60: https://github.com/heroku/buildpacks-jvm/actions/runs/6626786735/job/18000413851#step:10:10
In addition to fixing the error message, I've renamed the enum variants and variables to match the new name.
Lastly, I've updated the README to match the more concise release metadata style now used by all of our buildpacks (the repository URL is also a real example, to make it clearer that the URL shouldn't include the `docker://` prefix).
Fixes #168.
GUS-W-14355165.
> Fix error message shown when image repository metadata is missing

- Cargo.toml
- src/main.rs
As of the Cargo included in Rust 1.74, lints can now be configured in `Cargo.toml` across whole crates/workspaces:
https://blog.rust-lang.org/2023/11/16/Rust-1.74.0.html
https://doc.rust-lang.org/stable/cargo/reference/manifest.html#the-lints-section
Since this feature requires Rust 1.74, the MSRV has also been bumped.
GUS-W-14523770.
> Switch to Cargo.toml based lint configuration

- Cargo.toml
- clippy.toml
- src/main.rs
Enables some off-by-default lints that we already use in the `libcnb.rs` repository.
https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unreachable-pub
https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unsafe-code
https://rust-lang.github.io/rust-clippy/master/index.html#/panic_in_result_fn
https://rust-lang.github.io/rust-clippy/master/index.html#/unwrap_used
GUS-W-14523770.
> Enable additional rustc and Clippy lints

- .gitignore
- Cargo.lock
- Cargo.toml
As of Cargo 1.75 the `version` property in `Cargo.toml` is now optional, and if omitted is the same as having specified `version = "0.0.0"` and `publish = false`:
https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-175-2023-12-28
https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field
Therefore for crates that we do not publish, we can now remove both the `version` and `publish` properties, avoiding the need for the fake `0.0.0` version that differs from the actual buildpack version in `buildpack.toml`.
GUS-W-14821120.
> Simplify Cargo metadata for `publish = false` crates

- .github/workflows/_classic-buildpack-prepare-release.yml
- README.md
This new workflow is based on the prepare release workflow used by the classic Python buildpack:
https://github.com/heroku/heroku-buildpack-python/blob/main/.github/workflows/prepare-release.yml
However, as part of porting, the following changes have been made:
- The workflow now uses Git tags as the source of truth for the "existing" buildpack version, rather than the version from the buildpack registry. This allows the workflow to be used by classic buildpacks whose changelog/git tag versions are no longer in sync with the buildpack registry version (such as Ruby and PHP). This also saves callers of this workflow from having to pass the specific name/ID that the buildpack uses on the registry.
- There's a new optional `custom_update_command` input, which can be used by the Ruby …
> Add a "Prepare release" workflow for classic buildpacks

- Cargo.toml
The `version` and `publish` fields were removed in #181 since they are now optional for crates that are not published to crates.io.
However, even though this crate isn't published to crates.io, the `version` field is still used/set as part of the current GitHub Releases publishing process, which uses `cargo-bump` to generate an appropriate new version number based on the major/minor/patch workflow input.
Fixes:
```
$ cargo bump 0.3.10
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-bump-1.1.0/src/main.rs:57:14:
toml has version
```
Seen in:
https://github.com/heroku/languages-github-actions/actions/runs/7669085052/job/20902261440#step:9:10
> Add back the `version` field to Cargo.toml

- .github/workflows/_classic-buildpack-prepare-release.yml
Currently if the `git log` generated to populate the PR description contains more than one commit, the workflow fails with errors like:
```
Error: Unable to process file command 'output' successfully.
Error: Invalid format '- Migrate from CircleCI to GHA (#214)'
```
This is because of the GitHub Actions gotcha around multi-line strings when using `GITHUB_OUTPUT` (or `GITHUB_ENV`):
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
This didn't come up during testing, since the repo I tried with happened to only have a single commit on `main` since the last tag, and so didn't generate a multi-line `git log` output.
See also:
https://github.com/heroku/heroku-buildpack-nodejs/pull/1153
https://github.com/heroku/libcnb.rs/pull/692 …
> Fix multi-line `GITHUB_OUTPUT` error in classic buildpack prepare release workflow

- Cargo.lock
- Cargo.toml
- src/github/actions.rs
* Drops some unused `chrono` features, see: https://github.com/chronotope/chrono/blob/main/README.md#crate-features
* Switches from [rand](https://crates.io/crates/rand) to the lightweight [fastrand](https://crates.io/crates/rand) crate, since we don't need the much larger cryptographically secure library. (Other non-cryptographic crates we use, like `tempfile` use `fastrand` too.)
Reduces the number of transitive dependencies by 20.
GUS-W-15019814.
> Drop some unneeded dependencies

- .github/workflows/_buildpacks-release.yml
Now that we have the new Heroku-24 based builder (as of https://github.com/heroku/cnb-builder-images/pull/504), we should keep it up to date with releases, like we do for the other builders.
GUS-W-14673590.
> Add builder-24 to the list of builder manifests that are updated

- .github/workflows/_buildpacks-release.yml
Since we no longer want to be publishing new versions of the legacy builders, and so the manifests for them are being removed from the builder repo in:
https://github.com/heroku/cnb-builder-images/pull/514
GUS-W-15677907.
> Stop updating manifests of legacy builders

- Cargo.toml
- src/commands/generate_buildpack_matrix/command.rs
This PR reads `[[metadata.targets]]` from a composite buildpack's `buildpack.toml` to determine what targets the composite buildpack is intended to be compiled for.
We're not actually sure if `[[targets]]` is legal as a part of a composite buildpack descriptor, so libcnb.rs has not modeled it as noted here:
https://github.com/heroku/libcnb.rs/blob/a4e48fde0b502eec1ce1d0b811bb1ac61beed101/libcnb-data/src/buildpack/mod.rs#L182-L185
The multi-platform rfc seems to indicate that this will eventually be part of `package.toml`:
https://github.com/buildpacks/rfcs/blob/abd3ba28d7648e03a9c2074a88dae9fe3b069683/text/0000-multiarch-builders-and-package.md?plain=1#L754-L776
But `package.toml` is not a part of the spec, and this field isn't implemented in `libcnb.rs` or `pack` yet. Using it now would …
> Add support for composite buildpack targets during publication

- .github/workflows/_buildpacks-release.yml
Since upstream image publishing is broken and the images for the new versions haven't been published/tagged properly: https://cloud-native.slack.com/archives/C032YE21V1T/p1717723450552739
https://github.com/orgs/buildpacks/packages/container/actions%2Fregistry%2Frequest-add-entry/versions?filters%5Bversion_type%5D=tagged
This will be fixed upstream by:
https://github.com/buildpacks/github-actions/pull/284
However, in the meantime we can use the old version.
> Downgrade to request-add-entry Action v5.6.1

- .github/workflows/_buildpacks-prepare-release.yml
- .github/workflows/_buildpacks-release.yml
- .github/workflows/_classic-buildpack-prepare-release.yml
- .github/workflows/release.yml
The use-app-token action is deprecated: https://github.com/heroku/use-app-token-action/pull/17
Throws a warning on actions that use it:
GUS-W-15886232
> Use actions/create-github-app-token instead of heroku/use-app-token

- .github/workflows/_buildpacks-release.yml
- src/commands/generate_buildpack_matrix/command.rs
We're seeing some releases with extra `{os}-{arch}` suffixes on the `.cnb` files, and duplicated copies of `.cnb` files:
- https://github.com/heroku/buildpacks-procfile/releases/tag/v3.1.2
- https://github.com/heroku/buildpacks-python/releases/tag/v0.11.0
- https://github.com/heroku/buildpacks-python/releases/tag/v0.12.0
This seems to be happening because newer versions of pack with multi-arch support are detecting these buildpacks as multi-arch buildpacks, and thus tries to build a `"{os}-{arch}.cnb"` for each of the targets: https://github.com/buildpacks/pack/pull/2086/files#diff-f149889a3ad04f6ef0e49a7bc274d34be83c6e9ce07539c4ad4c65561fdc7bbaR184-R185
This PR forces `pack buildpack package` to use a `--target` argument, like `--target linux/amd64` which causes `pack` to skip a bunch of …
> Set target when packaging buildpack

- .github/workflows/_buildpacks-release.yml
This fix restores the safety of triggering the release automation on an existing release which was lost in the updates for publishing multi-arch Docker images in #194.
The buildpack matrix output can contain two variants of images to publish:
- A CNB with a single target. E.g.;
```json
{
"buildpack_id": "heroku/nodejs-function",
"buildpack_version": "3.2.6",
"buildpack_type": "composite",
"buildpack_dir": "/home/runner/work/buildpacks-nodejs/buildpacks-nodejs/meta-buildpacks/nodejs-function",
"targets": [
{
"os": "linux",
"arch": "amd64",
"rust_triple": "x86_64-unknown-linux-musl",
"oci_target": "linux/amd64",
"cnb_file": "heroku_nodejs-function.cnb",
"stable_tag": "docker.io/heroku/buildpack-nodejs-function:3.2.6",
"temporary_tag": …
```
> Restore safe Docker publishing

- .github/workflows/_buildpacks-prepare-release.yml
- .github/workflows/_buildpacks-release.yml
- .github/workflows/_classic-buildpack-prepare-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- README.md
Now that Ubuntu 24.04 images are available on GitHub Actions, we can update from the Ubuntu 22.04 images.
See also:
https://github.com/actions/runner-images/issues/9848
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
https://salesforce.quip.com/bu6UA0KImOxJ#temp:C:GZRd13d2ce2d455470495cbd34cf
GUS-W-16238120.
> Update CI to Ubuntu 24.04 runner images

- .github/workflows/_buildpacks-release.yml
When running `pack buildpack package` with a buildpack that has a `docker` dependency on a multi-arch image index like this:
```
[dependencies]
uri = "docker://heroku/buildpack-release-phase:1.0.3"
```
Pack defers the image resolution to docker. This works fine when packaging a buildpack for the host platform, but breaks when packaging for another architecture. The default docker image store (which pack uses) is not able to properly handle cross platform images. The error manifests like this:
```
ERROR: packaging dependencies (uri='docker://heroku/buildpack-release-phase:1.0.3',image=''): extracting from registry 'docker://heroku/buildpack-release-phase:1.0.3': extracting buildpacks from 'heroku/buildpack-release-phase:1.0.3': could not find label 'io.buildpacks.buildpackage.metadata'
``` …
> Arch specific dependencies

- .github/workflows/_buildpacks-release.yml
This morning we started seeing CNB release jobs fail during the step that installs the cross-compile dependencies, due to a 404 Not Found from the APT mirror, eg:
```
Get:26 http://azure.archive.ubuntu.com/ubuntu noble/main amd64 g++-aarch64-linux-gnu amd64 4:13.2.0-7ubuntu1 [962 B]
E: Failed to fetch mirror+file:/etc/apt/apt-mirrors.txt/pool/main/b/binutils/binutils-aarch64-linux-gnu_2.42-4ubuntu2.3_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
Fetched 56.3 MB in 30s (1886 kB/s)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
(https://github.com/heroku/buildpacks-jvm/actions/runs/13588383287/job/37988366601)
After opening a support ticket with Canonical, they suggested we run `apt-get update`, which did resolve the issue.
Whilst GitHub Actions …
> Run `apt-get update` before installing cross-compile deps

- .github/dependabot.yml
- .github/workflows/_buildpacks-prepare-release.yml
- .github/workflows/_buildpacks-release.yml
- .github/workflows/_classic-buildpack-prepare-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
The full-version Git tags used by Actions are mutable (as seen in recent events in the wider GitHub Actions community), so pinning third-party Actions to a SHA is recommended:
https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
The version tag has been added after the pin as a comment (as a readability aid) in a format that Dependabot will keep up to date: https://github.com/dependabot/dependabot-core/issues/4691
I've also enabled Dependabot grouping for GitHub Actions updates to reduce PR noise.
GUS-W-18051077.
> Pin SHA of third-party GitHub Actions

- .github/workflows/_buildpacks-prepare-release.yml
- .github/workflows/_buildpacks-release.yml
- .github/workflows/_classic-buildpack-prepare-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- README.md
As part of security-hardening our GHA workflows, this reduces the permissions granted to the automatically set `GITHUB_TOKEN` env var in GitHub Actions workflows to no more than what is required by that workflow.
See:
https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication
GUS-W-18053749.
> Reduce scopes granted to `GITHUB_TOKEN` in GitHub Actions workflows

- .github/workflows/ci.yml
- .github/workflows/release.yml
The Cargo `--locked` argument ensures that Cargo will fail with an error if `Cargo.lock` is out of sync with `Cargo.toml`, rather than the lockfile being silently updated.
As such, in CI we should always be using `--locked` for projects that have committed their lockfile to Git (which should be the case for most projects other than those that are libraries).
After seeing that `cnb-otel-collector` didn't use `--locked` in all cases, I audited all of our Rust repos and found others missing `--locked` too.
GUS-W-18062544.
> Add missing `--locked` to Cargo commands

- .github/workflows/_buildpacks-release.yml
Since our CNBs have started to drop support for Ubuntu 20.04 / Heroku-20 (since they have reached end-of-life), eg:
- https://github.com/heroku/buildpacks-python/pull/358
- https://github.com/heroku/buildpacks-ruby/pull/422
...and so we don't want the release automation to update to these new versions in `heroku/builder:20`.
GUS-W-14706143.
> Stop updating CNB versions in `heroku/builder:20`

- .github/workflows/_buildpacks-release.yml
This also helps work around a current bug/outage Docker Hub are having where deletion attempts fail with an error:
```json
{"message":"operation requires admin permissions","errinfo":{}}
```
This occurs even if the tags aren't there (so re-running the workflow doesn't work, even though it tries to remove different temporary tags in the re-run).
Assuming this bug remained, it would still cause a workflow failure upon first run, but a re-run (which hits the "already published to Docker Hub" check) would then succeed.
GUS-W-18970431
> Only unpublish temp tags off Docker Hub if they were created earlier

- .github/workflows/_buildpacks-release.yml
Since the builder no longer exists on CNB builder images `main` after:
https://github.com/heroku/cnb-builder-images/pull/782
GUS-W-19325110.
> Remove salesforce-functions builder from builders list
